- setup-gcloud/dist/index.js
- setup-gcloud/src/setup-gcloud.ts
This makes the action interface simpler, since the `service_account_email` argument is not
required when using a JSON service account key, it should be possible for the user to omit this option when it isn't needed.
[All tests passed](https://github.com/btorresgil/github-actions/commit/eb89c6b0ea48535b80574aee92c6ba8c94a0c4ef/checks?check_suite_id=314548720)
> Make service_account_email optional

- action.yml
Hi there 👋 Although it's recommended to keep actions in their own repos, this is a copy-paste of the `action.yml` from `setup-gcloud` to the top level of the repository, which will allow publishing `setup-gcloud` to the GitHub Marketplace.
If this PR is accepted as is, the action can be referenced in a workflow as either `uses: GoogleCloudPlatform/github-actions/setup-gcloud` or just `uses: GoogleCloudPlatform/github-actions`.
> Top level action.yml

- setup-gcloud/dist/index.js
- setup-gcloud/src/setup-gcloud.ts
The line which is written installGcloudSDK() does not have `await` operator.
So I fixed it.
> fix using installGcloudSDK()

- .github/workflows/setup-gcloud-it.yml
- .github/workflows/setup-gcloud.yml
- setup-gcloud/__tests__/integration-tests.sh
- setup-gcloud/dist/index.js
- setup-gcloud/src/install-util.ts
- setup-gcloud/src/setup-gcloud.ts
Added integration tests for setup-gcloud. GH Actions currently has a limitation which prevents the projection of secrets from the store into runs triggered by PRs by forks. This means that for the time being maintainers will have to manually create branches from PR forks they'd like to run integration tests against. I've communicated the issue to @imjohnbo and the fine folks at GH, and they're diligently working on a solution for us.
> Added integration tests for setup-gcloud action.

- setup-gcloud/README.md
Document the fact that turning on export_default_credentials will cause a file to be generated
Addresses https://github.com/GoogleCloudPlatform/github-actions/issues/65
> Document export_default_credentials file creation

- action.yml
- get-secretmanager-secrets/action.yml
- setup-gcloud/action.yml
There was some disparity around the author field and also some discrepancies between the root action.yaml and the setup-gcloud action.yaml. This also improve the description of some of the attributes.
> Unify action.yaml format

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
This adds an initial issue template (we can iterate on it in the future) to help reduce the back-and-forth with bug reports.
> Add GitHub issue template

- .github/workflows/get-secretmanager-secrets-it.yml
- .github/workflows/get-secretmanager-secrets.yml
- .github/workflows/setup-gcloud-it.yml
- .github/workflows/setup-gcloud.yml
This reduces the number of tests we need to run by mapping the tests to the files changed.
> Only run CI checks that correspond to changed files

- example-workflows/cloud-run/README.md
I was following the setup instructions for Cloud Run action, and felt like these steps were missing/ weren't clear to me in the instructions.
Please help me review - if it makes sense, I could add them to the other examples as well.
I changed the indentation to fix the list rendering.
> Add instructions to set up service account and repo secrets

- setup-gcloud/README.md
The workspace isn't shared in v1. Refs: GH-80.
> Document actions/checkout@v2 requirement

- .github/workflows/setup-gcloud-it.yml
- action.yml
- setup-gcloud/action.yml
This isn't technically necessary because the default is "latest", but I've noticed a lot of people copy-paste examples and then end up with an outdated gcloud version.
> Update to latest gcloud version in docs

- get-secretmanager-secrets/action.yml
without it you see this warning: `Unexpected input 'credentials', valid inputs are ['secrets']`
> add optional input (credentials)

- example-workflows/gae/.github/workflows/app-engine.yml
Application failed to deploy in CI environment for GAE example because it used the interactive deployment prompt.
Resolves issue #108.
> Issue #108: add '--quiet' flag to gae example

- appengine-deploy/action.yml
fixes #136 
Looks like are missing the `credentials` input in  appengine-deploy action.yml
> Add credentials to  appengine-deploy action.yml

- package-lock.json
- setup-gcloud/README.md
- setup-gcloud/dist/index.js
- setup-gcloud/src/setup-gcloud.ts
Reverts GoogleCloudPlatform/github-actions#148
As I kinda suspected but couldn't remember, there's a reason we use the action's temporary directory.
/cc @travisgroth @ViacheslavKudinov
> Revert "Use RUNNER_TEMP to export credentials"

- appengine-deploy/README.md
- appengine-deploy/dist/index.js
- appengine-deploy/src/main.ts
The action.yml specifies an `image_url` param, but `main.ts` is looking for an `image-url` parameter instead, and so any `image_url` passed in gets silently dropped. (And `image-url` isn't grammatically valid as an action-parameter identifier, so you can't just pass that in, either.)
I fixed `main.ts`, and ran `npm run build` to regenerate `dist/`. Also updated README.md to refer to the parameter as `image_url`.
> Fix appengine-deploy action to read from image_url param correctly

- deploy-cloudrun/README.md
The Cloud Run deploy example was using appengine repository. Fixed for cloudrun.
> Fixed wrong repo usage example

- .github/workflows/release-please.yml
- separates release-please action into 2 parts
- `release-pr` creates the release pr from a fork using robot account
- `github-release` which creates the release is done using regular token
- added `monorepo-tags` to identify individual action release-branch PRs. Example: https://github.com/bharathkkb/github-actions/pulls
> feat: separate steps for releas-please

- appengine-deploy/src/main.ts
The first URL is always matched with "https://cloud.google.com".
> Use last matched URL

- .github/workflows/setup-gcloud.yml
- setup-gcloud/README.md
- setup-gcloud/action.yml
- setup-gcloud/dist/index.js
- setup-gcloud/package-lock.json
- setup-gcloud/package.json
- setup-gcloud/src/index.ts
- setup-gcloud/src/setup-gcloud.ts
- setup-gcloud/tests/setup-gcloud.test.ts
Fixes GH-144
- Adds a new optional input to `setup-gcloud` which allows the caller to override the path at which the credentials are saved on disk. If not provided, the previous behavior (using `GITHUB_WORKSPACE`) is maintained.
- Adds tests for this action
> Add optional credentials_file_path input for setup-gcloud

- example-workflows/cloud-build/README.md
Fix [Cloud IAM roles](https://cloud.google.com/iam/docs/granting-changing-revoking-access#granting_access_to_a_service_account_for_a_resource) from `Cloud Build Admin` to `Cloud Run Admin`.
> Fix cloud build readme

- .github/workflows/setup-gcloud.yml
- setup-gcloud/README.md
- setup-gcloud/action.yml
- setup-gcloud/dist/index.js
- setup-gcloud/package-lock.json
- setup-gcloud/package.json
- setup-gcloud/src/index.ts
- setup-gcloud/src/setup-gcloud.ts
- setup-gcloud/tests/setup-gcloud.test.ts
PR #153 
UNIT
https://github.com/GoogleCloudPlatform/github-actions/runs/1300545920?check_suite_focus=true
https://github.com/GoogleCloudPlatform/github-actions/actions/runs/325114551
IT
https://github.com/GoogleCloudPlatform/github-actions/runs/1300545948?check_suite_focus=true
> feat: Add optional credentials_file_path input for setup-gcloud (#153)

- setup-gcloud/package-lock.json
- setup-gcloud/package.json
- setupGcloudSDK/package-lock.json
- setupGcloudSDK/package.json
@actions/tool-cache does not seem to use addPath or exportVariable but bumping to latest patched versions
> fix: bump @actions/tool-cache to 1.6.1

- setup-gcloud/tests/setup-gcloud.test.ts
`GITHUB_PATH` is required to activate new method of appending to path
https://github.com/actions/toolkit/blob/e7eb2c741847a05686a1b8df93dea4b244640b17/packages/core/src/core.ts#L67-L75
> fix: add GITHUB_PATH to unit test process stub

- .github/workflows/appengine-deploy-it.yml
- .github/workflows/deploy-cf-it.yml
- .github/workflows/deploy-cf-unit.yml
- .github/workflows/deploy-cloudrun-credentials-it.yml
- .github/workflows/deploy-cloudrun-it.yml
- .github/workflows/deploy-cloudrun.yml
- .github/workflows/get-gke-credentials-it.yml
- .github/workflows/get-gke-credentials-unit.yml
- .github/workflows/get-secretmanager-secrets-it.yml
- .github/workflows/upload-cloud-storage-it.yml
- appengine-deploy/README.md
- deploy-cloud-functions/README.md
- deploy-cloudrun/README.md
- example-workflows/cloud-build/.github/workflows/cloud-build.yml
- example-workflows/cloud-run/.github/workflows/cloud-run.yml
- example-workflows/gae/.github/workflows/app-engine.yml
- example-workflows/gce/.github/workflows/gce.yaml
- example-workflows/gke/.github/workflows/gke.yml
- get-secretmanager-secrets/README.md
- setup-gcloud/README.md
- upload-cloud-storage/README.md
Updated the action name to use the new format in all instances expect those related to the deprecation notice.
> Update action name

- example-workflows/README.md
> doc: update example workflows

- .github/workflows/setup-gcloud-it.yml
Integration tests were not running due to wrong branch name
> chore: fix branch name for integration tests

- example-workflows/cloud-run/README.md
- example-workflows/gae/README.md
Closes https://github.com/google-github-actions/setup-gcloud/pull/383
> Fix broken README links

- .eslintrc.js
- .prettierrc.js
- README.md
- dist/index.js
- package-lock.json
- package.json
- src/setup-gcloud.ts
- tests/setup-gcloud.test.ts
- tsconfig.json
This will ensure the credentials do no persist beyond the run, but are still available to all other steps in the job.
Also a few small fixes:
- Remove deprecated prettier config option
- Drop dependency on uuid and use crypto instead for generating filenames
- Write the credentials file securely
Fixes https://github.com/google-github-actions/setup-gcloud/issues/402
> Export credentials into RUNNER_TEMP instead of GITHUB_WORKSPACE

- .github/workflows/release-please.yml
This should ensure the lockfile doesn't change (I think).
> Run `run ci` instead of `npm install` in release please

- .github/workflows/release.yml
We haven't switched from master to main in this repo yet and this is blocking build. I will create a follow up PR once I rename the branch.
> chore: update branch name for release workflow

- .github/workflows/release.yml
- .github/workflows/setup-gcloud-it.yml
- .github/workflows/setup-gcloud.yml
- action.yml
fixes https://github.com/google-github-actions/setup-gcloud/issues/523
> feat: switch to node16

- src/setup-gcloud.ts
This can be overridden by setting an environment variable.
> feat: throw a very specific error when pinned to master

- README.md
Hello :wave:
Thank you for providing useful actions for GCP users!
I've confirmed that WIF is supported even for `gsutil` and `bq` commands. I also found [another post that commented WIF worked with the `gsutil` command](https://github.com/GoogleCloudPlatform/gsutil/issues/1407#issuecomment-1165320798).
So here I want to suggest a documentation update to provide the same description with [`google-github-actions/auth`](https://github.com/google-github-actions/auth).
refs https://github.com/google-github-actions/auth/pull/213
> Document that WIF is supported for gsutil and bq now

- .github/workflows/setup-gcloud-it.yml
> fix: cleanup integration tests

- src/setup-gcloud.ts
Thanks for releasing v1, it encourages me to keep using fresh releases!
Here I'll suggest a minor fix, which helps users to use the latest release instead of v0.
> fix: suggest v1 instead of v0

- example-workflows/cloud-build/.github/workflows/cloud-build.yml
- example-workflows/cloud-run/cloud-run.yml
- example-workflows/gae/app-engine.yml
- example-workflows/gce/.github/workflows/gce.yaml
- example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml
- example-workflows/gke/.github/workflows/gke.yml
> fix: update versions in examples

- README.md
- src/main.ts
Closes https://github.com/google-github-actions/setup-gcloud/issues/610
> Fix docs about component installation for system-provided

- README.md
Based on github's comments in https://github.com/actions/runner-images/issues/7101 it's my understanding that at some point the system-installed gcloud will no longer be included in the runners. When that happens, I assume any workflows with `skip_install: true` will stop working
(also fyi: the readme [references](https://github.com/google-github-actions/setup-gcloud#contributing) CONTRIBUTING.md, but that file doesn't exist)
> Add warning about `skip_install`

- README.md
Fixed a typo in the README.md's sample workflow. Changed 'job' to 'jobs' to align with the correct YAML syntax for GitHub Actions workflows.
> Fix typo in sample workflow shown in README.md.

- README.md
Fixes to readme for inaccurate guidance on setting Application Default Credentials.
https://github.com/google-github-actions/setup-gcloud/issues/685
> Fix ADC documentation, issue#685
