google-github-actions/setup-gcloud

setup-gcloud/README.md, setup-gcloud/action.yml
Follow up PR for: https://github.com/GoogleCloudPlatform/github-actions/pull/8
@btorresgil
=> Movidied action metadata and docs to reflect optional email param.

setup-gcloud/dist/index.js
=> Issue #21: Fix syntax error

setup-gcloud/dist/index.js
=> setup-cloud/dist/index.js syntax error fix

setup-gcloud/dist/index.js
It still has syntax errors.  I run `npm run build` to make `setup-gcloud/dist/index.js` up to date.
```
/home/runner/work/_actions/GoogleCloudPlatform/github-actions/master/setup-gcloud/dist/index.js:9176
? buffer.from && Uint8Array && buffer.from !== Uint8Array.from
^
SyntaxError: Unexpected token ?
at Module._compile (internal/modules/cjs/loader.js:718:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
at Module.load (internal/modules/cjs/loader.js:641:32)
at Function.Module._load (internal/modules/cjs/loader.js:556:12)
at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
at internal/main/run_main_module.js:17:11
##[error]Node run failed with exit code 1
```
=> Rebuild setup-gcloud/dist/index.js

.github/workflows/workflow.yml
notes:
https://github.com/actions/checkout/blob/master/README.md
=> use GitHub Actions checkout v2

setup-gcloud/__tests__/download-util.test.ts, setup-gcloud/__tests__/install-util.test.ts, setup-gcloud/dist/index.js, setup-gcloud/src/install-util.ts
=> Added metrics tracking user agent string

setup-gcloud/README.md, setup-gcloud/dist/index.js, setup-gcloud/src/setup-gcloud.ts
=> Made authentication optional

example-workflows/README.md, example-workflows/gke/.github/workflows/gke.yml, example-workflows/gke/README.md, example-workflows/gke/deployment.yml, example-workflows/gke/kustomization.yml, example-workflows/gke/nginx.conf, example-workflows/gke/service.yml
1) Added a top level README with set up steps and create a consistent variable names across examples
2) Updated GKE README
3) Fixed License
=> Updates to GKE workflow

example-workflows/gce/.github/gce.yaml, example-workflows/gce/Dockerfile, example-workflows/gce/README.md
GCE deployment currently focuses only on container-optimized VMs as noted in the instructions.
=> Add GCE workflow and instructions

example-workflows/cloud-run/README.md
fixes https://github.com/GoogleCloudPlatform/github-actions/issues/62
=> Add missing permission for cloud run build

setup-gcloud/README.md
Hi,
Just a small PR to document the very useful project_id option.
Let me know what you think about it.
=> Document the project_id input option

setup-gcloud/dist/index.js, setup-gcloud/src/setup-gcloud.ts
fixes: https://github.com/GoogleCloudPlatform/github-actions/issues/84
=> fix cached gcloud path

get-secretmanager-secrets/dist/index.js, get-secretmanager-secrets/package-lock.json, setup-gcloud/dist/index.js, setup-gcloud/package-lock.json
https://github.com/advisories/GHSA-vh95-rmgr-6w4m
=> Updated minimist to 1.2.5 to address security vulnerability

example-workflows/README.md, example-workflows/cloud-build/.dockerignore, example-workflows/cloud-build/.github/workflows/cloud-build.yml, example-workflows/cloud-build/Dockerfile, example-workflows/cloud-build/README.md, example-workflows/cloud-build/index.js, example-workflows/cloud-build/package-lock.json, example-workflows/cloud-build/package.json
=> add plain cloud build

.github/workflows/get-secretmanager-secrets-it.yml, .github/workflows/setup-gcloud-it.yml, action.yml, example-workflows/cloud-run/.github/workflows/cloud-run.yml, example-workflows/cloud-run/README.md, example-workflows/gae/.github/workflows/app-engine.yml, example-workflows/gae/README.md, example-workflows/gce/.github/workflows/gce.yaml, example-workflows/gce/README.md, example-workflows/gke/.github/workflows/gke.yml, example-workflows/gke/README.md, setup-gcloud/README.md, setup-gcloud/action.yml
=> Add clarity around service_account_email

example-workflows/gke/README.md
I feel I deserve a generous bounty for this one..
=> typo correction

example-workflows/gke/.github/workflows/gke.yml
Fixes #104 by adding user configurable `DEPLOYMENT_NAME` env var based on https://github.com/GoogleCloudPlatform/github-actions/issues/104#issuecomment-633748805
=> Fix deployment name issue in GKE workflow

package-lock.json, setup-gcloud/README.md, setup-gcloud/dist/index.js, setup-gcloud/src/setup-gcloud.ts
=> Use RUNNER_TEMP to export credentials

appengine-deploy/dist/index.js, appengine-deploy/src/main.ts
Before it would treat two values (like `app.yaml cron.yaml`) as a single entry and fail since a file like `"/some/path/app.yaml cron.yaml"` does not exist.
=> Fix support for multiple deliverables

.github/workflows/release-please.yml
- updates release please to use fork and custom robot account
- adds name of action to commit message
=> feat: release via fork

setup-gcloud/src/setup-gcloud.ts
Reprise of: https://github.com/GoogleCloudPlatform/github-actions/pull/163
=> Add version when looking for installed gcloud sdk 

.github/workflows/appengine-deploy-it.yml, .github/workflows/setup-gcloud-it.yml, setup-gcloud/src/setup-gcloud.ts
Fixed workflow files as well.
setup-gcloud IT passed: https://github.com/GoogleCloudPlatform/github-actions/runs/1300381937?check_suite_focus=true
appengine-deploy IT passed: https://github.com/GoogleCloudPlatform/github-actions/runs/1300381978?check_suite_focus=true
x-ref: https://github.com/GoogleCloudPlatform/github-actions/pull/209
=> feat: Add version when looking for installed gcloud sdk

example-workflows/gke/deployment.yml
Update `appVersion` from `apps/v1beta1` to `apps/v1`, add `selector.matchLabels.app`.
=> Update appversion, add selector

.github/workflows/release-please.yml
- remove builds for other actions except setup-gcloudm setupGcloudSDK
- remove releases for other actions except setup-gcloud
=> chore: remove builds and releases for other actions

.github/workflows/release-please.yml
based on https://github.com/google-github-actions/release-please-action/pull/121/ 
- fixes #93 
- pins release-please action to v2
=> fix: major/minor tags

action.yml
=> fix: add credentials_file_path to root action.yaml

example-workflows/gke/README.md
=> docs: Correct typo in readme

.github/workflows/appengine-deploy-it.yml, .github/workflows/deploy-cf-it.yml, .github/workflows/deploy-cf-unit.yml, .github/workflows/deploy-cloudrun-credentials-it.yml, .github/workflows/deploy-cloudrun-it.yml, .github/workflows/deploy-cloudrun.yml, .github/workflows/get-gke-credentials-it.yml, .github/workflows/get-gke-credentials-unit.yml, .github/workflows/get-secretmanager-secrets-it.yml, .github/workflows/upload-cloud-storage-it.yml, appengine-deploy/README.md, deploy-cloud-functions/README.md, deploy-cloudrun/README.md, example-workflows/cloud-build/.github/workflows/cloud-build.yml, example-workflows/cloud-run/.github/workflows/cloud-run.yml, example-workflows/gae/.github/workflows/app-engine.yml, example-workflows/gce/.github/workflows/gce.yaml, example-workflows/gke/.github/workflows/gke.yml, get-secretmanager-secrets/README.md, setup-gcloud/README.md, upload-cloud-storage/README.md
=> fix: Update action names (#250)

example-workflows/gce/README.md
=> docs: Typo in readme

package.json
Cloud SDK package 0.2.0 has ARM support. Should fix #329
=> chore: update cloud SDK dep

package-lock.json
I'm working on something else, but this is resulting in a large diff, so I'm doing it separately.
=> Upgrade to latest lockfile version

.github/workflows/setup-gcloud-it.yml, README.md, package-lock.json, package.json, src/setup-gcloud.ts
fixes https://github.com/google-github-actions/setup-gcloud/issues/396
=> feat: Support WIF creds

.github/workflows/setup-gcloud-it.yml, package-lock.json, package.json
xref https://github.com/google-github-actions/setup-cloud-sdk/pull/50
fixes [#422 ](https://github.com/google-github-actions/setup-gcloud/issues/418)
=> fix: fix auth precedence

README.md
fixes https://github.com/google-github-actions/setup-gcloud/issues/422
=> chore: fix docs pinned version

README.md
=> Pin auth to v0

README.md, example-workflows/cloud-build/.github/workflows/cloud-build.yml, example-workflows/cloud-run/cloud-run.yml, example-workflows/gae/app-engine.yml, example-workflows/gce/.github/workflows/gce.yaml, example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml, example-workflows/gke/.github/workflows/gke.yml
=> Support WIF in examples workflows

.github/workflows/setup-gcloud-it.yml, src/setup-gcloud.ts, tests/setup-gcloud.test.ts
fixes https://github.com/google-github-actions/auth/issues/73
=> fix: support export auth export with envvar for backwards compat

.github/workflows/release.yml, .github/workflows/setup-gcloud-it.yml, .github/workflows/setup-gcloud.yml, .gitignore, README.md, example-workflows/README.md, example-workflows/cloud-build/.github/workflows/cloud-build.yml, example-workflows/cloud-build/README.md, example-workflows/gce/.github/workflows/gce.yaml, example-workflows/gce/README.md
=> Rename workflows and branches to main

.github/workflows/release.yml, .github/workflows/setup-gcloud-it.yml, .github/workflows/setup-gcloud.yml, .gitignore, README.md, example-workflows/README.md, example-workflows/cloud-build/.github/workflows/cloud-build.yml, example-workflows/cloud-build/README.md, example-workflows/gce/.github/workflows/gce.yaml, example-workflows/gce/README.md
Reverts google-github-actions/setup-gcloud#449
=> Revert "Rename workflows and branches to main"

.github/workflows/release.yml
=> chore: set release action branch to "master"

package.json
=> chore: minify build

README.md
Closes https://github.com/google-github-actions/setup-gcloud/issues/315
=> docs: make it clearer that most auth inputs are deprecated

README.md
=> chore: note that gsutil and bq don't support WIF yet

README.md
Fixes https://github.com/google-github-actions/setup-gcloud/issues/475
=> docs: add note about minimum gcloud version

example-workflows/cloud-build/README.md, example-workflows/cloud-run/README.md, example-workflows/gae/README.md, example-workflows/gce/README.md, example-workflows/gke-kustomize/README.md, example-workflows/gke/README.md
I removed unnatural words in the README.
=> chore: remove unnecessary words in the README

README.md
=> doc: add example for install_components

package-lock.json, package.json, src/setup-gcloud.ts, tests/setup-gcloud.test.ts
This should resolve issues where output is swallowed
Closes #492
Closes #491
Closes #490 
Closes #489
Closes #488
=> chore: update deps and use new cloud sdk

package-lock.json, package.json
updating sdk to pull in https://github.com/google-github-actions/setup-cloud-sdk/pull/94. Should fix #504
=> chore: update setup-cloud-sdk

example-workflows/cloud-build/.github/workflows/cloud-build.yml
According the README file within the `cloud-build` examples I updates the Github Actions Workflow file with the mentioned Github Actions Secrets.
=> fix: update secrets according to readme
